Factory/Models/BreadCrumbs.cs
using System.Globalization;
using System.Reflection;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;

// sourced from https://techyian.github.io/2020-03-02-aspnetcore-breadcrumbs/ //
// adapted to fit AspNetCore.Mvc by Henry Oberholtzer //
namespace Factory.Models;

public class BreadcrumbActionFilter : ActionFilterAttribute
{
  public override void OnActionExecuted(ActionExecutedContext filterContext)
  {
    List<Breadcrumb> breadcrumbs = ConfigureBreadcrumb(filterContext);

    Controller controller = filterContext.Controller as Controller;
    controller.ViewBag.Breadcrumbs = breadcrumbs;

    base.OnActionExecuted(filterContext);
  }

  private static List<Breadcrumb> ConfigureBreadcrumb(ActionExecutedContext context)
  {
    List<Breadcrumb> breadcrumbList = new();
    string homeControllerName = "Home";

    breadcrumbList.Add(new Breadcrumb
    {
      Text = "Home",
      Action = "Index",
      Controller = homeControllerName,
      Active = true
    });

    if (context.HttpContext.Request.Path.HasValue)
    {
      string[] pathSplit = context.HttpContext.Request.Path.Value.Split("/");
      TextInfo info = CultureInfo.CurrentCulture.TextInfo;

      for (int i = 0; i < pathSplit.Length; i++)
      {
        string pathName = info.ToTitleCase(pathSplit[i]);

        if (string.IsNullOrEmpty(pathName) || string.Compare(pathName, homeControllerName, true) == 0)
        {
          continue;
        }

        Type controller = GetControllerType(pathName + "Controller");
        if (controller != null)
        {
          var indexMethod = controller.GetMethod("Index");

          if (indexMethod != null)
          {
            breadcrumbList.Add(new Breadcrumb
            {
              Text = CamelCaseSpacing(pathName),
              Action = "Index",
              Controller = pathSplit[i],
              Active = true
            });

            if (i + 1 < pathSplit.Length && string.Compare(info.ToTitleCase(pathSplit[i + 1]), "Index", true) == 0)
            {
              breadcrumbList.LastOrDefault().Active = false;

              return breadcrumbList;
            }
          }
        }

        if (i - 1 > 0)
        {
          var prevController = GetControllerType(info.ToTitleCase(pathSplit[i - 1]) + "Controller");
          if (prevController != null)
          {
            MethodInfo method = prevController.GetMethod(pathName, new Type [] { typeof(int)});
            if(method == null)
            {
              method = prevController.GetMethod(pathName, Array.Empty<Type>());
            }
            if (method != null)
            {
              breadcrumbList.Add(new Breadcrumb
              {
                Text = CamelCaseSpacing(pathName),
                Action = pathSplit[i],
                Controller = pathSplit[i - 1]
              });
            }
          }
        }
      }
    }
    breadcrumbList.LastOrDefault().Active = false;
    return breadcrumbList;
  }

  private static Type GetControllerType(string name)
  {
    Type controller = null;
    try
    {
      controller = Assembly.GetCallingAssembly().GetType("Factory.Controllers." + name);
    }
    catch
    { }

    return controller;
  }

  private static string CamelCaseSpacing(string s)
  {
    var r = new Regex(@"
        (?<=[A-Z])(?=[A-Z][a-z]) |
        (?<=[^A-Z])(?=[A-Z]) |
        (?<=[A-Za-z])(?=[^A-Za-z])", RegexOptions.IgnorePatternWhitespace);

    return r.Replace(s, " ");
  }

    public void OnActionExecuting(ActionContext context)
    {
        throw new NotImplementedException();
    }
}

public class Breadcrumb
{
  public string Text { get; set; }
  public string Action { get; set; }

  public string Controller { get; set; }

  public bool Active { get; set; }

  public Breadcrumb() {}

  public Breadcrumb(string text, string action, string controller, bool active)
  {
    Text = text;
    Action = action;
    Controller = controller;
    Active = active;
  }
}

Factory/Controllers/MakesController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using Microsoft.EntityFrameworkCore;

namespace Factory.Controllers;

[BreadcrumbActionFilter]
public class MakesController : Controller
{
  private readonly FactoryContext _db;

  public MakesController(FactoryContext db)
  {
    _db = db;
  }
  
  public Dictionary <string, object> MakeFormModel(Make make, string action)
  {
    return new Dictionary<string, object> {
      {"Make", make},
      {"Action", action}
    };
  }

  public bool CheckForDuplicates(Make make)
  {
#nullable enable
  Make? existing = _db.Makes.FirstOrDefault(m => m.Name.ToLower() == make.Name.ToLower());
#nullable disable
  if (existing == null)
  {
    return false;
  }
  else
  {
    return true;
  }
  }
  public async Task<IActionResult> Index()
  {
    List<Make> makes = await _db.Makes
      .Include(m => m.MakeVehicles)
      .Include(m => m.MakeMechanics)
      .ToListAsync();
    return View(makes);
  }

  public ActionResult Create()
  {
    
    return View(MakeFormModel(new Make(), "Create"));
  }

  [HttpPost]
  public ActionResult Create(Make make)
  {
    if(!ModelState.IsValid)
    {
      return View(MakeFormModel(make, "Create"));
    }
    if (CheckForDuplicates(make) == false)
    {
      _db.Makes.Add(make);
      _db.SaveChanges();
    }
    return RedirectToAction("Index");
  }

  public ActionResult Edit(int id)
  {
    Make target = _db.Makes.FirstOrDefault(m => m.MakeId == id);
    return View(MakeFormModel(target, "Edit"));
  }

  [HttpPost]
  public ActionResult Edit(Make make)
  {
    if(!ModelState.IsValid)
    {
      return View(MakeFormModel(make, "Edit"));
    }
    if (CheckForDuplicates(make) == false)
    {
      _db.Makes.Update(make);
      _db.SaveChanges();
    }
    return RedirectToAction("Index");
  }

  [HttpPost]
  public ActionResult Delete(int id)
  {
    Make target = _db.Makes
    .Include(m => m.MakeMechanics)
    .Include(m => m.MakeVehicles)
    .FirstOrDefault(m => m.MakeId == id);
    if(target.MakeVehicles.Count == 0 && target.MakeMechanics.Count == 0)
    {
      _db.Makes.Remove(target);
      _db.SaveChanges();
    }
    return RedirectToAction("Index");
  }
  public ActionResult Details(int id)
  {
    Make target = _db.Makes
    .Include(m => m.MakeMechanics)
    .ThenInclude(mm => mm.Mechanic)
    .ThenInclude(m => m.VehicleMechanics)
    .Include(m => m.MakeVehicles)
    .ThenInclude(mv => mv.Vehicle)
    .ThenInclude(v => v.VehicleMechanics)
    .FirstOrDefault(m => m.MakeId == id);
    return View(target);
  }

}

Factory/Controllers/VehiclesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Factory.Models;
using Factory.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace Factory.Controllers;

[BreadcrumbActionFilter]
public class VehiclesController : Controller
{
    private readonly FactoryContext _db;

    public VehiclesController(FactoryContext db)
    {
        _db = db;
    }

    public Dictionary<string, object> FormModel(VehicleViewModel vehicleViewModel, SelectList makeSelectList, string action)
    {
        return new Dictionary<string, object> {
            {"VehicleViewModel", vehicleViewModel},
            {"makeSelectList", makeSelectList},
            {"Action", action}
        };
    }

    public VehicleViewModel VehicleViewModelMap(Vehicle v)
    {
        return new VehicleViewModel
        {
            VehicleId = v.VehicleId,
            LicensePlate = v.LicensePlate,
            MakeId = v.MakeVehicles.First().MakeId,
            Model = v.Model,
            ModelYear = v.ModelYear,
            Color = v.Color,
            Condition = v.Condition
        };
    }

    public Vehicle VehicleViewModelMap(VehicleViewModel vehicleViewModel, Make make)
    {
        return new Vehicle
        {
            VehicleId = vehicleViewModel.VehicleId,
            LicensePlate = vehicleViewModel.LicensePlate,
            Model = vehicleViewModel.Model,
            ModelYear = vehicleViewModel.ModelYear,
            Color = vehicleViewModel.Color,
            Condition = vehicleViewModel.Condition,
            YearMakeModelPlate = $"{vehicleViewModel.ModelYear} {make.Name} {vehicleViewModel.Model} | {vehicleViewModel.LicensePlate}",
            DateAdded = DateTime.Now
        };
    }

    public Vehicle VehicleViewModelMap(VehicleViewModel vehicleViewModel, Vehicle vehicle, Make make)
    {
        vehicle.LicensePlate = vehicleViewModel.LicensePlate;
        vehicle.Model = vehicleViewModel.Model;
        vehicle.ModelYear = vehicleViewModel.ModelYear;
        vehicle.Color = vehicleViewModel.Color;
        vehicle.Condition = vehicleViewModel.Condition;
        vehicle.YearMakeModelPlate = $"{vehicleViewModel.ModelYear} {make.Name} {vehicleViewModel.Model} | {vehicleViewModel.LicensePlate}";
        return vehicle;
    }
    public async Task<IActionResult> Index()
    {
        List<Vehicle> vehicles = await _db.Vehicles.Include(v => v.VehicleMechanics).ToListAsync();
        return View(vehicles);
    }

    public async Task<IActionResult> Create()
    {
        List<Make> makeList = await _db.Makes.OrderBy(m => m.Name).ToListAsync();
        SelectList makeSelectList = new(makeList, "MakeId", "Name");
        return View(FormModel(new VehicleViewModel(), makeSelectList, "Create"));
    }


    [HttpPost]
    public async Task<IActionResult> Create(VehicleViewModel vehicleViewModel)
    {
        if (!ModelState.IsValid)
        {
            List<Make> makeList = await _db.Makes.OrderBy(m => m.Name).ToListAsync();
            SelectList makeSelectList = new(makeList, "MakeId", "Name");
            Dictionary<string, object> model = FormModel(vehicleViewModel, makeSelectList, "Create");
            return View(model);
        }
        Make makeReference = new();
        if (!string.IsNullOrEmpty(vehicleViewModel.NewMake))
        {
#nullable enable // check and see if NewMake exists & does not match anything in the DB
            Make? existing = await _db.Makes.FirstOrDefaultAsync(m => m.Name == vehicleViewModel.NewMake);
#nullable disable
            if (existing == null)
            {
                // if it does not match, add a new Make, and get the makes Id
                Make newMake = new()
                {
                    Name = vehicleViewModel.NewMake
                };
                _db.Makes.Add(newMake);
                await _db.SaveChangesAsync();
                vehicleViewModel.MakeId = newMake.MakeId;
                makeReference = newMake;
            }
            else
            {
                // if it does match something in the database, get the match Id
                vehicleViewModel.MakeId = existing.MakeId;
                makeReference = existing;
            }
        }

        // create a new vehicle
        Vehicle newVehicle = VehicleViewModelMap(vehicleViewModel, makeReference);
        _db.Vehicles.Add(newVehicle);
        await _db.SaveChangesAsync();
        // add new MakeVehicle
        MakeVehicle makeVehicle = new()
        {
            MakeId = vehicleViewModel.MakeId,
            VehicleId = newVehicle.VehicleId
        };
        _db.MakeVehicles.Add(makeVehicle);
        await _db.SaveChangesAsync();
        return RedirectToAction("Index");

    }

    public async Task<IActionResult> Edit(int id)
    {
        Vehicle v = await _db
        .Vehicles
        .Include(v => v.MakeVehicles)
        .FirstOrDefaultAsync(vehicle => vehicle.VehicleId == id);
        List<Make> makeList = await _db.Makes.OrderBy(m => m.Name).ToListAsync();
        SelectList makeSelectList = new(makeList, "MakeId", "Name");
        foreach (SelectListItem item in makeSelectList)
        {
            if (item.Value == v.MakeVehicles.First().MakeId.ToString())
            {
                item.Selected = true;
            }
        }
        return View(FormModel(VehicleViewModelMap(v), makeSelectList, "Edit"));
    }

    [HttpPost]
    public async Task<IActionResult> Edit(VehicleViewModel vehicleViewModel)
    {
        if (!ModelState.IsValid)
        {
            List<Make> makeList = await _db.Makes.OrderBy(m => m.Name).ToListAsync();
            SelectList makeSelectList = new(makeList, "MakeId", "Name");
            foreach (SelectListItem item in makeSelectList)
            {
                if (item.Value == vehicleViewModel.MakeId.ToString())
                {
                    item.Selected = true;
                }
            }
            return View(FormModel(vehicleViewModel, makeSelectList, "Edit"));
        }
        Vehicle vehicleToEdit = await _db.Vehicles
        .Include(v => v.MakeVehicles)
        .ThenInclude(mv => mv.Make)
        .FirstOrDefaultAsync(vehicle => vehicle.VehicleId == vehicleViewModel.VehicleId);

        Make makeReference = vehicleToEdit.MakeVehicles.First().Make;


        if (!string.IsNullOrEmpty(vehicleViewModel.NewMake))
        {
#nullable enable // check and see if NewMake exists & does not match anything in the DB
            Make? existing = await _db.Makes.FirstOrDefaultAsync(m => m.Name == vehicleViewModel.NewMake);
#nullable disable
            if (existing == null)
            {
                // if it does not match, add a new Make, and get the makes Id
                Make newMake = new()
                {
                    Name = vehicleViewModel.NewMake
                };
                _db.Makes.Add(newMake);
                await _db.SaveChangesAsync();
                vehicleViewModel.MakeId = newMake.MakeId;
                makeReference = newMake;
            }
            else
            {
                // if it does match something in the database, get the match Id
                vehicleViewModel.MakeId = existing.MakeId;
                makeReference = existing;
            }

        }
        else if (vehicleViewModel.MakeId != vehicleToEdit.MakeVehicles.First().MakeId && vehicleViewModel.MakeId != 0)
        {
#nullable enable // check and see if NewMake exists & does not match anything in the DB
            Make? existing = await _db.Makes.FirstOrDefaultAsync(m => m.MakeId == vehicleViewModel.MakeId);
#nullable disable
            if (existing != null)
            {
                makeReference = existing;
            }
        }
        if (vehicleViewModel.MakeId != 0)
        {
            IQueryable<MakeVehicle> mvList = _db.MakeVehicles.Where(mv => mv.VehicleId == vehicleToEdit.VehicleId);
            foreach (MakeVehicle mV in mvList)
            {
                _db.MakeVehicles.Remove(mV);
            }
            await _db.SaveChangesAsync();
            MakeVehicle makeVehicle = new()
            {
                MakeId = vehicleViewModel.MakeId,
                VehicleId = vehicleToEdit.VehicleId
            };
            _db.MakeVehicles.Add(makeVehicle);
            await _db.SaveChangesAsync();
        }

        _db.Vehicles.Update(VehicleViewModelMap(vehicleViewModel, vehicleToEdit, makeReference));
        await _db.SaveChangesAsync();
        return RedirectToAction("Details", new { id = vehicleToEdit.VehicleId });

    }

    public async Task<IActionResult> Details(int id)
    {
        Vehicle vehicle = await _db
        .Vehicles
        .Include(v => v.VehicleMechanics)
        .ThenInclude(join => join.Mechanic)
        .Include(v => v.MakeVehicles)
        .FirstOrDefaultAsync(v => v.VehicleId == id);

        List<Mechanic> unselected = await _db.Mechanics
        .Include(m => m.VehicleMechanics)
        .Include(m => m.MakeMechanics)
        .Where(m => !m.VehicleMechanics.Any(vm => vm.VehicleId == id))
        .Where(m => m.MakeMechanics.Any(i => i.MakeId == vehicle.MakeVehicles.First().MakeId))
        .ToListAsync();
        SelectList mechanicsSelectList = new(unselected, "MechanicId", "LastName");


        Dictionary<string, object> model = new() {
            {"selectList", mechanicsSelectList},
            {"joinEntity", new VehicleMechanic()},
            {"vehicle", vehicle}
        };
        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Delete(int id)
    {
        Vehicle vehicle = await _db.Vehicles.FirstOrDefaultAsync(v => v.VehicleId == id);
        _db.Vehicles.Remove(vehicle);
        await _db.SaveChangesAsync();
        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> AssignMechanic(VehicleMechanic vm)
    {
#nullable enable
        VehicleMechanic? joinEntity = await _db.VehicleMechanics

Factory/Views/Shared/_AddMechanic.cshtml
@{
  SelectList list = Model["selectList"];
  VehicleMechanic vm = Model["joinEntity"];
  int vehicleId = Model["vehicle"].VehicleId;
}

@if (list.Count() == 0)
{
  <select disabled>
    <option>No Mechanics Available</option>
  </select>
    <button type="submit" disabled>Assign</button>
}
else
{
<form asp-controller="Vehicles" asp-action="AddMechanic" method="post">
  <input asp-for=@vm.VehicleId value=@vehicleId type="hidden" />
  <select asp-for=@vm.MechanicId asp-items=@list></select>
  <button type="submit">Assign</button>
</form>
}

Factory/Views/Shared/_Breadcrumbs.cshtml
@if (ViewBag.Breadcrumbs != null)
{
  <nav aria-label="breadcrumb" class="breadcrumbs">
    <ol>
      @foreach (Breadcrumb b in ViewBag.Breadcrumbs as List<Breadcrumb>)
      {
        if(b.Active)
        {
          <li class="breadcrumb-active">
            <a asp-action="@b.Action" asp-controller="@b.Controller">@b.Text</a>
          </li>
        }
        else
        {
          <li class="breadcrumb-inactive" aria-current="page"><p>@b.Text</p></li>
        }
      }
    </ol>
  </nav>
}

Factory/Views/Shared/_Header.cshtml
<header id="header">
  <a asp-controller="Home" asp-action="Index"><h1>RepairFactory</h1></a>
  @await Html.PartialAsync("_Navigation")
</header>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>@ViewBag.PageTitle - RepairFactory</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link href="~/css/styles.css" rel="stylesheet" runat="server" asp-append-version="true"/>
  <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Kode+Mono:wght@400..700&display=swap" rel="stylesheet">
</head>

<body>
  @await Html.PartialAsync("_Header")
  <div id="main-container">
    @await Html.PartialAsync("_Breadcrumbs")
    @RenderBody()
  </div>

  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/js/scripts.js"></script>
  @await RenderSectionAsync("_ValidationScriptsPartial", required: false)
</body>

</html>

Factory/Views/Shared/_MechanicList.cshtml
@model List<Mechanic>

<table class="table">
  <thead>
    <th scope="col">Name</th>
    <th scope="col">Makes</th>
    <th scope="col">Vehicles</th>
  </thead>
  <tbody>
    @foreach (Mechanic mechanic in Model)
    {
      <tr class="table-row">
        <td>
          <a class="expanded" asp-controller="Mechanics" asp-action="Details" asp-route-id=@mechanic.MechanicId>
          </a>
            @mechanic.FirstName @mechanic.LastName

        </td>
        <td>@mechanic.MakeMechanics.Count</td>
        <td>@mechanic.VehicleMechanics.Count</td>
      </tr>
    }
  </tbody>
    <tfoot>
  @if (Model.Count == 0)
    {
      <tr class="table-row" ><th colspan="3">No mechanics have been added.</th></tr>
    }
  </tfoot>
</table>

Factory/Views/Shared/_Navigation.cshtml
<nav id="nav">
      <a asp-controller="Mechanics" asp-action="Index">
        <li class="btn-nav">Mechanics</li>
      </a>
      <a asp-controller="Vehicles" asp-action="Index">
        <li class="btn-nav">Vehicles</li>
      </a>
      <a asp-controller="Makes" asp-action="Index">
        <li class="btn-nav">Makes</li>
      </a>
</nav>

Factory/Views/Shared/_RemoveMechanic.cshtml
@model Vehicle

<div>
@if (Model.VehicleMechanics.Count == 0) {
  <li>No mechanics assigned.</li>
}
@foreach (VehicleMechanic vm in Model.VehicleMechanics)
{
  Mechanic m = vm.Mechanic;
  <li>
  <a asp-controller="Mechanics" asp-action="Details" asp-route-id=@m.MechanicId>@m.FirstName @m.LastName</a>
  <form asp-controller="Vehicles" asp-action="RemoveMechanic" method="post">
    <input type="hidden" name="id" value=@vm.VehicleMechanicId />
    <button type="submit">Unassign</button>
  </form>
  </li>
}
</div>

Factory/Views/Shared/_VehicleList.cshtml
@model List<Vehicle>
<table class="table">
<thead>
    <th scope="col">Name</th>
    <th scope="col">Mechanics</th>
</thead>
  <tbody>


    @foreach (Vehicle v in Model)
    {
      <tr class="table-row">
        <td>
          <a class="expanded" asp-controller="Vehicles" asp-action="Details" asp-route-id=@v.VehicleId>
          </a>
            @v.YearMakeModelPlate

        </td>
        <td>@v.VehicleMechanics.Count</td>
      </tr>
    }
  </tbody>
  <tfoot>
  @if (Model.Count == 0)
    {
      <tr class="table-row" ><th colspan="3">No vehicles have been added.</th></tr>
    }
  </tfoot>
</table>