Factory/Models/Make.cs
using System.ComponentModel.DataAnnotations;

namespace Factory.Models;

public class Make
{
  [Range(0, int.MaxValue)]
  public int MakeId { get; set; }

  [StringLength(255, ErrorMessage = "The {0} cannot be longer than {1} characters")]
  [Required]
  public string Name { get; set; }

  public List<MakeMechanic> MakeMechanics { get; set; }

  public List<MakeVehicle> MakeVehicles { get; set; }

}

Factory/Controllers/MakesController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using Microsoft.EntityFrameworkCore;

namespace Factory.Controllers;

[BreadcrumbActionFilter]
public class MakesController : Controller
{
  private readonly FactoryContext _db;

  public MakesController(FactoryContext db)
  {
    _db = db;
  }
  
  public Dictionary <string, object> MakeFormModel(Make make, string action)
  {
    return new Dictionary<string, object> {
      {"Make", make},
      {"Action", action}
    };
  }

  public bool CheckForDuplicates(Make make)
  {
#nullable enable
  Make? existing = _db.Makes.FirstOrDefault(m => m.Name.ToLower() == make.Name.ToLower());
#nullable disable
  if (existing == null)
  {
    return false;
  }
  else
  {
    return true;
  }
  }
  public async Task<IActionResult> Index()
  {
    List<Make> makes = await _db.Makes
      .Include(m => m.MakeVehicles)
      .Include(m => m.MakeMechanics)
      .ToListAsync();
    return View(makes);
  }

  public ActionResult Create()
  {
    
    return View(MakeFormModel(new Make(), "Create"));
  }

  [HttpPost]
  public ActionResult Create(Make make)
  {
    if(!ModelState.IsValid)
    {
      return View(MakeFormModel(make, "Create"));
    }
    if (CheckForDuplicates(make) == false)
    {
      _db.Makes.Add(make);
      _db.SaveChanges();
    }
    return RedirectToAction("Index");
  }

  public ActionResult Edit(int id)
  {
    Make target = _db.Makes.FirstOrDefault(m => m.MakeId == id);
    return View(MakeFormModel(target, "Edit"));
  }

  [HttpPost]
  public ActionResult Edit(Make make)
  {
    if(!ModelState.IsValid)
    {
      return View(MakeFormModel(make, "Edit"));
    }
    if (CheckForDuplicates(make) == false)
    {
      _db.Makes.Update(make);
      _db.SaveChanges();
    }
    return RedirectToAction("Index");
  }

  [HttpPost]
  public ActionResult Delete(int id)
  {
    Make target = _db.Makes
    .Include(m => m.MakeMechanics)
    .Include(m => m.MakeVehicles)
    .FirstOrDefault(m => m.MakeId == id);
    if(target.MakeVehicles.Count == 0 && target.MakeMechanics.Count == 0)
    {
      _db.Makes.Remove(target);
      _db.SaveChanges();
    }
    return RedirectToAction("Index");
  }
  public ActionResult Details(int id)
  {
    Make target = _db.Makes
    .Include(m => m.MakeMechanics)
    .ThenInclude(mm => mm.Mechanic)
    .ThenInclude(m => m.VehicleMechanics)
    .Include(m => m.MakeVehicles)
    .ThenInclude(mv => mv.Vehicle)
    .ThenInclude(v => v.VehicleMechanics)
    .FirstOrDefault(m => m.MakeId == id);
    return View(target);
  }

}

Factory/Controllers/MechanicsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Factory.Models;
using Factory.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace Factory.Controllers;

[BreadcrumbActionFilter]
public class MechanicsController : Controller
{
  private readonly FactoryContext _db;

  public MechanicsController(FactoryContext db)
  {
    _db = db;
  }
  public SelectList MakeSelectList()
  {
    List<Make> makeList = _db.Makes.OrderBy(m => m.Name).ToList();
    return new SelectList(makeList, "MakeId", "Name");
  }

  public SelectList MakeSelectList(List<int> selected)
  {
    List<Make> makeList = _db.Makes.OrderBy(m => m.Name).ToList();
    SelectList selectList = new(makeList, "MakeId", "Name");
    foreach (SelectListItem i in selectList)
    {
      if (selected.Contains(int.Parse(i.Value)))
      {
        i.Selected = true;
      }
    }
    return selectList;
  }


  public async Task<IActionResult> Index()
  {
    List<Mechanic> mechanics = await _db.Mechanics.Include(m => m.VehicleMechanics).Include(m => m.MakeMechanics).ToListAsync();
    return View(mechanics);
  }

  public ActionResult Create()
  {
    return View(new MechanicFormViewModel(MakeSelectList()));
  }

  [HttpPost]
  public async Task<IActionResult> Create(MechanicFormViewModel model)
  {
    if (!ModelState.IsValid)
    {
      model.MakeSelectList = MakeSelectList(model.SelectedMakes);
      return View(model);
    }
    Mechanic newMechanic = model.ToMechanic();
    _db.Mechanics.Add(newMechanic);
    await _db.SaveChangesAsync();
    if(model.SelectedMakes.Count > 0)
    {
      foreach (int i in model.SelectedMakes)
      {
        MakeMechanic newMakeMechanic = new()
        {
          MakeId = i,
          MechanicId = newMechanic.MechanicId
        };
        _db.MakeMechanics.Add(newMakeMechanic);
      }
      await _db.SaveChangesAsync();
    }
    return RedirectToAction("Details", new { id = newMechanic.MechanicId});
  }

  public async Task<IActionResult> Details(int id)
  {

    Mechanic mechanic = await _db
    .Mechanics
    .Include(m => m.VehicleMechanics)
    .ThenInclude(join => join.Vehicle)
    .Include(m => m.MakeMechanics)
    .ThenInclude(mm => mm.Make)
    .FirstOrDefaultAsync(m => m.MechanicId == id);

    List<int> approvedVehicles = mechanic.MakeMechanics.Select(mm => mm.MakeId).ToList();

    List<Vehicle> unselected = await _db.Vehicles
    .Include(v => v.VehicleMechanics)
    .Include(v => v.MakeVehicles)
    .Where(v => !v.VehicleMechanics.Any(vm => vm.MechanicId == id))
    .Where(v => approvedVehicles.Any(i => i == v.MakeVehicles.First().MakeId))
    .ToListAsync();
    
    SelectList vehiclesSelectList = new(unselected, "VehicleId", "YearMakeModelPlate");

    Dictionary<string, object> model = new() {
            {"selectList", vehiclesSelectList},
            {"joinEntity", new VehicleMechanic()},
            {"mechanic", mechanic}
        };
    return View(model);
  }

  public async Task<IActionResult> Edit(int id)
  {
    Mechanic thisMechanic = await _db
    .Mechanics
    .Include(m => m.MakeMechanics)
    .FirstOrDefaultAsync(m => m.MechanicId == id);
    List<int> makeIds = thisMechanic.MakeMechanics.Select(mm => mm.MakeId).ToList();
    return View(new MechanicFormViewModel(thisMechanic, MakeSelectList(makeIds), true));
  }
  [HttpPost]
  public async Task<IActionResult> Edit(MechanicFormViewModel model)
  {
    if (!ModelState.IsValid)
    {
      model.MakeSelectList = MakeSelectList(model.SelectedMakes);
      return View(model);
    }
    Mechanic thisMechanic = await _db
    .Mechanics
    .Include(m => m.MakeMechanics)
    .FirstOrDefaultAsync(m => m.MechanicId == model.MechanicId);
    foreach (MakeMechanic mm in thisMechanic.MakeMechanics)
    {
      _db.MakeMechanics.Remove(mm);
    }
    _db.SaveChanges();
    foreach (int i in model.SelectedMakes)
    {
      MakeMechanic newMakeMechanic = new()
      {
        MakeId = i,
        MechanicId = model.MechanicId
      };
      _db.MakeMechanics.Add(newMakeMechanic);
    }
    _db.Mechanics.Update(model.ToMechanic(thisMechanic));
    await _db.SaveChangesAsync();
    return RedirectToAction("Details", new { id = model.MechanicId });
  }

  [HttpPost]
  public async Task<IActionResult> Delete(int id)
  {
    Mechanic thisMechanic = await _db
    .Mechanics
    .FirstOrDefaultAsync(m => m.MechanicId == id);
    _db.Mechanics.Remove(thisMechanic);
    await _db.SaveChangesAsync();
    return RedirectToAction("Index");
  }

  [HttpPost]
  public async Task<IActionResult> AssignVehicle(VehicleMechanic vm)
  {
#nullable enable
    VehicleMechanic? joinEntity = await _db.VehicleMechanics
    .FirstOrDefaultAsync(join => join.VehicleId == vm.VehicleId && join.MechanicId == vm.MechanicId);
#nullable disable
    if (joinEntity == null && vm.VehicleId != 0)
    {
      _db.VehicleMechanics.Add(vm);
      await _db.SaveChangesAsync();
      return RedirectToAction("Details", new { id = vm.MechanicId });
    }
    return RedirectToAction("Details", new { id = vm.MechanicId });
  }

  [HttpPost]
  public async Task<IActionResult> UnassignVehicle(int id)
  {
    VehicleMechanic joinEntity = await _db.VehicleMechanics.FirstOrDefaultAsync(vm => vm.VehicleMechanicId == id);
    int mechanicId = joinEntity.MechanicId;
    _db.VehicleMechanics.Remove(joinEntity);
    await _db.SaveChangesAsync();
    return RedirectToAction("Details", new { id = mechanicId });
  }
}

Factory/Views/Makes/Create.cshtml
@await Html.PartialAsync("_MakeForm")

Factory/Views/Makes/Details.cshtml
@model Make
@{
  List<Vehicle> vehicles = Model.MakeVehicles.Select(mv => mv.Vehicle).ToList();
  List<Mechanic> mechanics = Model.MakeMechanics.Select(mv => mv.Mechanic).ToList();
}

<h1>@Model.Name</h1>
<nav id="nav" class="nav-left">
  <a asp-controller="Makes" asp-action="Edit" asp-route-id="@Model.MakeId">
    <li class="btn-nav">Edit</li>
  </a>
</nav>
<hr />
<h3>Vehicles In Shop</h3>
@await Html.PartialAsync("_VehicleList", vehicles)
<h3>Licensed Mechanics</h3>
@await Html.PartialAsync("_MechanicList", mechanics)

Factory/Views/Makes/Edit.cshtml
@await Html.PartialAsync("_MakeForm")

Factory/Views/Makes/Index.cshtml
@model List<Make>

<h1>All Makes</h1>
<nav id="nav-left">
  <a asp-controller="Mechanics" asp-action="Create">
    <li class="btn-nav">Add New</li>
  </a>
</nav>
<hr />
@await Html.PartialAsync("_MakeList")

Factory/Views/Makes/_MakeForm.cshtml
@{
  Make make = Model["Make"];
  string action = Model["Action"];
  string buttonText = "Add";
  if (Model["Action"] == "Edit")
  {
    buttonText = "Save";
  }
}

<form class="form" asp-controller="Makes" asp-action=@action method="post">
  @if(action == "Edit")
  {
    <input asp-for="@make.MakeId" type="hidden" />
  }
  <div class="form-group">
    <label asp-for="@make.Name"></label><br />
    <input asp-for="@make.Name" type="text" placeholder="Make Name" /><br />
    <span asp-validation-for="@make.Name"></span><br />
  </div>
  <button class="button" type="submit">@buttonText</button>
</form>

Factory/Views/Makes/_MakeList.cshtml
@model List<Make>

<table class="table">
<thead>
    <th scope="col">Name</th>
    <th scope="col">Mechanics</th>
    <th scope="col">In Shop</th>
</thead>
  <tbody>
    @foreach (Make m in Model)
    {
      <tr class="table-row">
        <td>
          <a class="expanded" asp-controller="Makes" asp-action="Details" asp-route-id=@m.MakeId>
          </a>
            @m.Name
        </td>
        <td>@m.MakeMechanics.Count</td>
        <td>@m.MakeVehicles.Count</td>
      </tr>
    }
  </tbody>
    <tfoot>
  @if (Model.Count == 0)
    {
      <tr class="table-row" ><th colspan="3">No makes have been added.</th></tr>
    }
  </tfoot>
</table>